[package]
name = "vello_sparse_shaders"
# When updating, also update the version in the workspace dependency in the root Cargo.toml
version = "0.0.6"
description = "Provide compilation of wgsl to glsl to support the WebGL `vello_hybrid` backend."
categories = ["rendering", "graphics"]
keywords = ["2d", "vector-graphics"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
all-features = true
# There are no platform specific docs.
default-target = "x86_64-unknown-linux-gnu"
targets = []

[dependencies]
naga = { workspace = true, features = ["wgsl-in", "glsl-out"], optional = true }

[build-dependencies]
naga = { workspace = true, features = ["wgsl-in", "glsl-out"], optional = true }

[features]
glsl = ["dep:naga"]

[lints]
workspace = true
