[package]
name = "usvg-viewer"
version = "0.1.0"
license = "MIT/Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
byte-unit = "4.0"
clap = { version = "4.1.0", features = ["derive"] }
dialoguer = "0.10"
generic-array = "0.14"
hex-literal = "0.3"
pollster = "0.2.5"
sha2 = "0.10"
ureq = "2.6"
usvg = "0.28"
vello = { path = "../../" }
wgpu = "0.14"
winit = "0.27.5"
