[package]
name = "demo_svg"
description = "Render a usvg document to a Vello scene"
categories = ["rendering", "graphics"]
keywords = ["2d", "vector-graphics", "vello"]
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
vello = { path = "../../" }
usvg = "0.37.0"
