[package]
name = "vello_example_scenes"
description = "Vello Example Scenes."
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[features]
default = []
cpu = ["dep:vello_cpu", "parley_draw/vello_cpu"]

[dependencies]
bytemuck = { workspace = true, features = [] }
smallvec = { workspace = true }
vello_hybrid = { workspace = true }
vello_common = { workspace = true, features = ["pico_svg", "png"] }
image = { workspace = true, features = ["jpeg"] }
vello_cpu = { workspace = true, optional = true }
parley = { version = "0.5.0", default-features = false, features = ["std", "system"] }
parley_draw = { workspace = true, features = ["std", "vello_hybrid"] }
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
log = { workspace = true }
