[package]
name = "vello_svg"
description = "Render a usvg document to a Vello scene"
categories = ["rendering", "graphics"]
keywords = ["2d", "vector-graphics", "vello"]
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
vello = { path = "../../" }
usvg = { version = "0.40", default-features = false }
