[package]
name = "vello_sparse_tests"
description = "The test suite for vello_cpu and vello_hybrid"
categories = ["rendering", "graphics"]
keywords = ["2d", "vector-graphics"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false
autotests = false

[[test]]
name = "tests"
path = "tests/mod.rs"

[dependencies]
vello_api = { workspace = true }
vello_common = { workspace = true, features = ["std"] }
vello_cpu = { workspace = true, features = ["multithreading", "std", "f32_pipeline"] }
vello_hybrid = { workspace = true }
parley_draw = { workspace = true, features = ["std", "vello_cpu", "vello_hybrid"] }
fearless_simd = { workspace = true, features = [
    "force_support_fallback", # We require the `force_support_callback` feature to test the fallback path.
] }
wgpu = { workspace = true, default-features = true }
pollster = { workspace = true }
vello_dev_macros = { workspace = true }
bytemuck = { workspace = true }
image = { workspace = true, features = ["png"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
skrifa = { workspace = true }
smallvec = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
oxipng = { workspace = true, features = ["freestanding", "parallel"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-test = "0.3.56"
web-sys = { version = "0.3.83", features = [
    "HtmlCanvasElement",
    "WebGl2RenderingContext",
    "Document",
    "Window",
    "Element",
    "HtmlElement",
    "HtmlImageElement",
    "Blob",
    "BlobPropertyBag",
    "Url",
    "Response",
] }
wasm-bindgen = "0.2.106"
wasm-bindgen-futures = "0.4.56"
# Required for introspecting the built WASM binary.
wasmparser = "0.235.0"

[features]
webgl = ["vello_hybrid/webgl"]

[lints]
workspace = true
