[package]
name = "simple_sdl2"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

# The dependencies here are independent from the workspace versions
[dependencies]
# When using this example outside of the original Vello workspace,
# remove the path property of the following Vello dependency requirement.
vello = { version = "0.7.0", path = "../../vello" }
pollster = "0.4.0"
sdl2 = { version = "0.37.0", features = ["raw-window-handle", "bundled"] }
