[package]
name = "vello_hybrid_winit"
description = "An example showing Vello Hybrid using winit."
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
winit = { workspace = true }
wgpu = { workspace = true, default-features = true }
vello_common = { workspace = true }
vello_hybrid = { workspace = true }
vello_example_scenes = { workspace = true }
pollster = { workspace = true }
