[package]
name = "piet-gpu"
version = "0.1.0"
authors = ["Raph Levien <raph.levien@gmail.com>"]
description = "A compute-centric GPU 2D renderer."
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies.piet-gpu-hal]
path = "../piet-gpu-hal"

[dependencies]
png = "0.16.2"
